version: "3.7"

services:
  mysql:
    container_name: 'bookstore_mysql'
    image: 'mysql:8'
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - 'bookstore-db:/var/lib/mysql'

volumes:
  bookstore-db:
