server:
  servlet:
    contextPath: /bookstore

spring:
  banner:
    location: 'classpath:/assets/banner.txt'
  datasource:
    username: user
    password: password
    url: 'jdbc:mysql://localhost:3306/bookstore'
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'

rm:
  spring-events:
    async: false

